dbt_project:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DATABASE') }}"
      host: "{{ env_var('POSTGRES_HOST') }}"
      pass: "{{ env_var('POSTGRES_PASS') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: "{{ env_var('POSTGRES_THREADS') }}"
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: dev
